version: '3'

services:

  nginx:
    container_name: apineu-nginx
    image: nginx
    volumes:
      - ../..:/apineu
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - default
      - nginx-frontproxy

  php:
    container_name: apineu-php
    hostname: apineu-server
    build: ./php
    image: apineu/php
    working_dir: /apineu/example/backend
    volumes:
      - ../..:/apineu
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ts:
    container_name: apineu-ts
    hostname: apineu-ts
    image: apineu/node
    working_dir: /client
    volumes:
      - ../../apineu-client:/client
    command: "npm run dev"

  vue:
    container_name: apineu-vue
    hostname: apineu-client
    build: ./node
    image: apineu/node
    working_dir: /apineu/example/frontend
    volumes:
      - ../..:/apineu

  mysql:
    container_name: apineu-mysql
    image: mariadb
    volumes:
      - apineu-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - '23306:3306'


networks:
  nginx-frontproxy:
    external: true

volumes:
  apineu-mysql:
    driver: local
